<?php
/**
 * Locale data for 'el_GR'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2013 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2014 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '8245',
  'numberSymbols' => 
  array (
    'decimal' => ',',
    'group' => '.',
    'list' => ',',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'e',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '[#E0]',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'AUD' => 'A$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => '$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'GRD' => 'Δρχ',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Ιανουαρίου',
      2 => 'Φεβρουαρίου',
      3 => 'Μαρτίου',
      4 => 'Απριλίου',
      5 => 'Μαΐου',
      6 => 'Ιουνίου',
      7 => 'Ιουλίου',
      8 => 'Αυγούστου',
      9 => 'Σεπτεμβρίου',
      10 => 'Οκτωβρίου',
      11 => 'Νοεμβρίου',
      12 => 'Δεκεμβρίου',
    ),
    'abbreviated' => 
    array (
      1 => 'Ιαν',
      2 => 'Φεβ',
      3 => 'Μαρ',
      4 => 'Απρ',
      5 => 'Μαϊ',
      6 => 'Ιουν',
      7 => 'Ιουλ',
      8 => 'Αυγ',
      9 => 'Σεπ',
      10 => 'Οκτ',
      11 => 'Νοε',
      12 => 'Δεκ',
    ),
    'narrow' => 
    array (
      1 => 'Ι',
      2 => 'Φ',
      3 => 'Μ',
      4 => 'Α',
      5 => 'Μ',
      6 => 'Ι',
      7 => 'Ι',
      8 => 'Α',
      9 => 'Σ',
      10 => 'Ο',
      11 => 'Ν',
      12 => 'Δ',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'Ι',
      2 => 'Φ',
      3 => 'Μ',
      4 => 'Α',
      5 => 'Μ',
      6 => 'Ι',
      7 => 'Ι',
      8 => 'Α',
      9 => 'Σ',
      10 => 'Ο',
      11 => 'Ν',
      12 => 'Δ',
    ),
    'abbreviated' => 
    array (
      1 => 'Ιαν',
      2 => 'Φεβ',
      3 => 'Μάρ',
      4 => 'Απρ',
      5 => 'Μάι',
      6 => 'Ιούν',
      7 => 'Ιούλ',
      8 => 'Αύγ',
      9 => 'Σεπ',
      10 => 'Οκτ',
      11 => 'Νοέ',
      12 => 'Δεκ',
 